### ISSUE TITLE
ItemAndBlockGeoLayer is unable to render item models that use the "neoforge:item_layers" loader

### ISSUE THREAD

**Issue by Nitespring** [bernie-g/geckolib#592]
https://pastebin.com/7UyjV3Vp

https://docs.neoforged.net/docs/resources/client/models/modelloaders/

The same could be true for other custom model loaders and for their Forge counterparts

**Comment by Nitespring** [comment]
same problem for forge 1.21 for "forge:item_layers"

		at TRANSFORMER/darkestsouls@1.0.1.5/github.nitespring.darkestsouls.client.render.entity.mob.church.doctor.ChurchDoctorGeoRenderer.render(ChurchDoctorGeoRenderer.java:52)

	GeckoLib 4 (geckolib), Version: 4.5.5
		Issue tracker URL: https://github.com/bernie-g/geckolib/issues
		at TRANSFORMER/geckolib@4.5.5/software.bernie.geckolib.renderer.GeoRenderer.createVerticesOfQuad(GeoRenderer.java:322)

**Comment by NordAct** [comment]
I've got similar error with custom [Animatable](https://github.com/NordAct/useless-reptile/blob/1.21/src/main/java/nordmods/uselessreptile/client/util/DragonEquipmentAnimatable.java) (i use Yarn btw).
Found temporary solution in [restoring buffer if it's not building](https://github.com/NordAct/useless-reptile/blob/5076d4fef2125bb79b9398630cd77ece656ab524/src/main/java/nordmods/uselessreptile/client/renderer/base/DragonEquipmentRenderer.java#L83). (accessed `building` with access widener).
It doesn't happen if I try to apply problematic layers to entity model. As comment above says, it happens only when either [BannerLayer](https://github.com/NordAct/useless-reptile/blob/1.21/src/main/java/nordmods/uselessreptile/client/renderer/layers/BannerLayer.java) (which is based upon `BlockAndItemGeoLayer`) and [DragonPassengerLayer](https://github.com/NordAct/useless-reptile/blob/1.21/src/main/java/nordmods/uselessreptile/client/renderer/layers/DragonPassengerLayer.java). Both work similarly and both cause stop building right after either item or entity in layer is rendered. I couldn't find the exact cause of this, but I just know that it does that.

Considering that it all worked just fine in 1.20.x, I suspect it's somehow related to whatever Mojang did to rendering again in 1.21

**Comment by Tslat** [comment]
> Considering that it all worked just fine in 1.20.x, I suspect it's somehow related to whatever Mojang did to rendering again in 1.21

Yeah Geckolib didn't change its internal rendering in any way in 1.21 - so it's definitely a change by mojang
What's weird is it still shouldn't affect anything, but it obviously is

I haven't had the chance to look yet, but my current assumption is that the buffer is being pushed because of a change of rendertype, which is causing it to stop building.
What's odd though is that this is not new behaviour - and that's how buffers have always worked, so I'm not sure why this is suddenly a problem now

Either way I don't think it'll be a particularly hard fix, I just want to try make sure I have it right before I do

**Comment by Tslat** [comment]
I am.. having trouble replicating it

![image](https://github.com/bernie-g/geckolib/assets/7098525/0c89837c-79a3-46fe-be23-cf2fd678827f)

**Comment by Tslat** [comment]
Fixed in 4.5.6

**Comment by seelderr** [comment]
I downloaded version 4.5.6 and I'm still encountering this issue:
https://pastebin.com/S9ig3A4i

**Comment by iron431** [comment]
occuring on 4.5.6:
https://gist.github.com/iron431/3987575f3a767bb77e17e81b0fdb079f
via `ItemArmorGeoLayer`:
https://github.com/iron431/irons-spells-n-spellbooks/blob/1.21/src/main/java/io/redspace/ironsspellbooks/entity/mobs/HumanoidRenderer.java#L46
